
services:

  db:
    image: postgres
    container_name: kata_client_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: clients_db
    ports:
      - 6000:5432 #Usando 6000 para evitar conflicto con postgres local


    volumes: #Permite que los datos de PostgreSQL persistan aunque el contenedor se elimine.
      - kata_client_postgres_data:/var/lib/postgresql/data

volumes:
  kata_client_postgres_data: