
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: kata_client_app
    environment:
      - DB_NAME=clients_db
      - FLASK_ENV=development
      - DB_USER=postgres
      - DB_PASSWORD=postgres_password
      - DB_HOST=db
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: kata_client_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: clients_db
    ports:
      - "5432:5432"


    volumes: #Permite que los datos de PostgreSQL persistan aunque el contenedor se elimine.
      - kata_client_postgres_data:/var/lib/postgresql/data

volumes:
  kata_client_postgres_data: