
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: kata_client_app
    environment:
      - DATABASE_NAME=kata_client_db
      - FLASK_ENV=development
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres_password
      - DATABASE_HOST=db
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: kata_client_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: kata_client_db
    ports:
      - "6000:5032"# Usando 6000 para evitar conflitos con instalacion postgres local. Cambiar a 5032 posteriormente.


    volumes: #Permite que los datos de PostgreSQL persistan aunque el contenedor se elimine.
      - kata_client_postgres_data:/var/lib/postgresql/data

volumes:
  kata_client_postgres_data: